# This is a basic workflow to help you get started with Actions

name: AwesomeDevStreamSite

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
        with:
          submodules: true
      - name: Build Site
        uses: chabad360/hugo-actions@master

      - name: Azure Blob Storage Upload
        uses: bacongobbler/azure-blob-storage-upload@v1.1.0
        with:
          source_dir: "public"
          container_name: "$web"
          connection_string: ${{ secrets.TWITCHSA }}
          sync: true
